language: haxe
sudo: false
haxe:
 - development

install:
 - haxelib install hxnodejs
 - haxelib install yaml
 - haxelib install compiletime
 - haxelib git plist https://github.com/back2dos/plist

script:
 - haxe build.hxml

 - cd syntaxes
 - npm install vscode-textmate
 - haxe all.hxml
